name: SMP
version: '${version}'
main: plugins.nate.smp.SMP
api-version: 1.20
depend:
  - Essentials
  - CoreProtect
  - WorldEdit
  - WorldGuard

commands:
  plugins:
    usage: /<command>
  pl:
    usage: /<command>
  bukkit:plugins:
    usage: /<command>
#  claim:
#    description: Get the claiming tool
#    usage: /<command>
  smp:
    usage: /<command>
  dev:
    usage: /<command>
  say:
    usage: /<command>

permissions:
  smp.chestlock.bypass:
    description: Allows bypassing of chest locks.
    default: op
  smp.reload:
    description: Reloads plugin
    default: op